# Generated by Django 5.0 on 2024-01-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, default='406271f912a04e8aa4f6f6a85b84a769', max_length=255, null=True),
        ),
    ]
