# Generated by Django 5.0 on 2024-01-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_alter_order_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, default='904f290721d24689a103ce6e850d50f8', max_length=255, null=True),
        ),
    ]
