# Generated by Django 5.0 on 2024-01-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0011_alter_order_tracking_id_alter_product_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='order_products', to='ecommerce_app.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, default='cb4f9d1b73134c369c295c41b36684b3', max_length=255, null=True),
        ),
    ]
