# Generated by Django 5.0 on 2024-01-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0012_alter_order_products_alter_order_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='ecommerce_app.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, default='0195af5ea7554851a433577447e2e39c', max_length=255, null=True),
        ),
    ]
