# Generated by Django 5.0 on 2024-01-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0015_remove_coupon_user_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, default='645f86eee2d7461ebd1dc8827eb50d78', max_length=255, null=True),
        ),
    ]
