# Generated by Django 5.0 on 2024-01-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0017_contactmessage_alter_order_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, default='7faac88aee3b410a9c9da43b1cc80297', max_length=255, null=True),
        ),
    ]
