# Generated by Django 5.0.3 on 2024-03-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0020_alter_order_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, default='9d3b69ee06664e3e83ed059740ae2dc9', max_length=255, null=True),
        ),
    ]
